import os
import json
from datetime import datetime
from ai.llm_client import query_llm

class ReportGenerator:
    """
    自动化测试报告生成引擎
    负责将 Trace 交互轨迹转化为由 AI 总结的业务测试报告
    """
    @staticmethod
    def generate(trace, log_file=None, output_dir="artifacts/reports"):
        """
        生成完整的 Markdown 报告
        """
        os.makedirs(output_dir, exist_ok=True)
        spec_id = trace.metadata.spec_id or "unknown"
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        report_filename = f"report_{spec_id}_{timestamp}.md"
        report_path = os.path.join(output_dir, report_filename)

        # 1. 提取核心统计数据
        stats = {
            "test_name": trace.metadata.url or trace.metadata.spec_id,
            "status": trace.result.status if trace.result else "unknown",
            "confidence": trace.result.confidence if trace.result else 0.0,
            "start_time": trace.metadata.start_time,
            "end_time": datetime.now().isoformat(),
            "total_steps": len(trace.steps),
            "error_message": trace.result.error_message if trace.result else None
        }

        # 2. 构造 AI 总结提示词
        summary_content = ReportGenerator._get_ai_summary(trace)

        # 3. 构造 Markdown 内容
        md_content = ReportGenerator._build_md(stats, summary_content, trace)

        # 4. 写入文件
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(md_content)
        
        return report_path

    @staticmethod
    def _get_ai_summary(trace):
        """
        调用 LLM 对测试过程进行业务层面的总结
        """
        mission_steps = []
        findings = []
        
        for i, step in enumerate(trace.steps, 1):
            status_icon = "✅" if step.verification and step.verification.result == 'pass' else "❌"
            mission_steps.append(f"Step {i}: {step.instruction} -> {status_icon} {step.verification.reason if step.verification else 'No verification'}")
            
            # 记录坏点 (Assert 失败)
            if step.verification and step.verification.result != 'pass':
                findings.append(f"- 业务坏点: 在执行 '{step.instruction}' 时验证失败，原因: {step.verification.reason}")

        system_prompt = "你是一个专业的自动化测试分析师。请根据提供的测试步骤和验证结果，总结本次测试的‘测试要点’、‘执行结论’以及‘发现的问题’。使用中文，保持专业、精炼。"
        user_prompt = f"""
测试目标: {trace.metadata.url}
执行轨迹记录:
{chr(10).join(mission_steps)}

请基于以上原始数据，生成一个排版精美的总结报告片断。包含以下部分：
### 📝 测试要点总结
(总结本次测试覆盖了哪些业务功能点)

### 🔍 关键发现与坏点
(如果没有发现问题，请说明‘未发现明显业务异常’；如果有，请详细列出)

### 💡 结论建议
(对系统健壮性的评价及后续建议)
"""
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]
        
        summary = query_llm(messages)
        if summary.startswith("Error"):
            return "### ⚠️ AI 总结不可用\n(API 调用失败，请检查配置)"
        return summary

    @staticmethod
    def _build_md(stats, ai_summary, trace):
        """
        组装最终的 Markdown 字符串
        """
        status_color = "green" if stats['status'] == 'pass' else "red"
        status_text = "通过 (PASS)" if stats['status'] == 'pass' else "失败 (FAIL)"
        
        template = f"""# 自动化测试执行报告

> [!NOTE]
> 本报告由 AI 测试引擎根据运行时真实轨迹自动生成。

## 📊 执行概览
- **测试名称**: {stats['test_name']}
- **执行结论**: <span style="color:{status_color};font-weight:bold;">{status_text}</span>
- **执行耗时**: {stats['start_time']} -> {stats['end_time']}
- **步骤总数**: {stats['total_steps']}
- **置信度**: {stats['confidence']}
{f"- **错误信息**: `{stats['error_message']}`" if stats['error_message'] else ""}

---

{ai_summary}

---

## 📸 关键步骤回放图 (Selected)
"""
        # 提取有截图的步骤
        screenshots_section = ""
        for i, step in enumerate(trace.steps, 1):
            for sub in step.sub_actions:
                if sub.get('action') == 'screenshot':
                   path = sub.get('value')
                   # 转换为相对路径以便在文档中引用
                   rel_path = path.replace('\\', '/')
                   screenshots_section += f"### 步骤 {i} 现场取证\n![Step {i} Screenshot](../../{rel_path})\n\n"
        
        if not screenshots_section:
            screenshots_section = "_（本次执行未触发自动截屏）_\n"

        template += screenshots_section
        
        template += "\n---\n*Report generated by AI Test Runner V3.1*"
        return template
